# Generated by Django 2.0 on 2020-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kddcup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('srv_count', models.IntegerField()),
                ('dst_host_count', models.IntegerField()),
                ('dst_host_srv_sount', models.IntegerField()),
                ('same_srv_rate', models.IntegerField()),
                ('dst_host_same_src_port_rate', models.DecimalField(decimal_places=3, max_digits=8)),
                ('dst_host_serror_rate', models.IntegerField()),
                ('label', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='mydb',
        ),
    ]
