# Generated by Django 2.0 on 2020-03-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20200322_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kddcup',
            options={'verbose_name': 'kddcup数据集'},
        ),
        migrations.AlterModelTable(
            name='kddcup',
            table='kddcup',
        ),
    ]
