# Generated by Django 2.0 on 2020-03-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20200328_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
