# Generated by Django 2.0 on 2020-03-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dir', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '文件列表',
                'db_table': 'document',
            },
        ),
    ]
