# Generated by Django 2.0 on 2020-03-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dir',
            field=models.CharField(max_length=150),
        ),
    ]
