# Generated by Django 2.0 on 2020-03-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0009_auto_20200329_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('srv_count', models.IntegerField()),
                ('dst_host_count', models.IntegerField()),
                ('dst_host_srv_count', models.IntegerField()),
                ('same_srv_rate', models.IntegerField()),
                ('dst_host_same_src_port_rate', models.FloatField()),
                ('dst_host_serror_rate', models.IntegerField()),
                ('label', models.IntegerField()),
            ],
            options={
                'verbose_name': '数据',
                'db_table': 'data',
            },
        ),
    ]
